#  __  ___  ___________    ____ ____    __    ____  ______   .______       _______       _______.
# |  |/  / |   ____\   \  /   / \   \  /  \  /   / /  __  \  |   _  \     |       \     /       |
# |  '  /  |  |__   \   \/   /   \   \/    \/   / |  |  |  | |  |_)  |    |  .--.  |   |   (----`
# |    <   |   __|   \_    _/     \            /  |  |  |  | |      /     |  |  |  |    \   \    
# |  .  \  |  |____    |  |        \    /\    /   |  `--'  | |  |\  \----.|  '--'  |.----)   |   
# |__|\__\ |_______|   |__|         \__/  \__/     \______/  | _| `._____||_______/ |_______/    

# https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = waybar
exec-once = nm-applet --indicator

exec = awww-daemon
exec = awww img ~/arch/assets/aurora.png