# .___  ___.   ______   .__   __.  __  .___________.  ______   .______          _______.
# |   \/   |  /  __  \  |  \ |  | |  | |           | /  __  \  |   _  \        /       |
# |  \  /  | |  |  |  | |   \|  | |  | `---|  |----`|  |  |  | |  |_)  |      |   (----`
# |  |\/|  | |  |  |  | |  . `  | |  |     |  |     |  |  |  | |      /        \   \    
# |  |  |  | |  `--'  | |  |\   | |  |     |  |     |  `--'  | |  |\  \----.----)   |   
# |__|  |__|  \______/  |__| \__| |__|     |__|      \______/  | _| `._____|_______/    

# https://wiki.hypr.land/Configuring/Monitors/

env = GDK_SCALE, 1
env = GDK_DPI_SCALE, 1

monitor = , preferred, auto, 1
