# .______    _______ .______      .___  ___.  __       _______.     _______. __    ______   .__   __.      _______.
# |   _  \  |   ____||   _  \     |   \/   | |  |     /       |    /       ||  |  /  __  \  |  \ |  |     /       |
# |  |_)  | |  |__   |  |_)  |    |  \  /  | |  |    |   (----`   |   (----`|  | |  |  |  | |   \|  |    |   (----`
# |   ___/  |   __|  |      /     |  |\/|  | |  |     \   \        \   \    |  | |  |  |  | |  . `  |     \   \    
# |  |      |  |____ |  |\  \----.|  |  |  | |  | .----)   |   .----)   |   |  | |  `--'  | |  |\   | .----)   |   
# | _|      |_______|| _| `._____||__|  |__| |__| |_______/    |_______/    |__|  \______/  |__| \__| |_______/    

# https://wiki.hypr.land/Configuring/Permissions/

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
