declare -a DELETE_FILES=(

)

declare -a KEEP_FILES=(

)

declare -a DOTFILES=(
    ".config/btop"
    ".config/dunst"
    ".config/fastfetch"
    ".config/gtk-3.0"
    ".config/hypr"
    ".config/kitty"
    ".config/nvim"
    ".config/qt5ct"
    ".config/qt6ct"
    ".config/rofi"
    ".config/waybar"
    ".config/wlogout"
    ".config/code-flags.conf"
    ".config/starship.toml"
    ".sddm/catppuccin-mocha-mauve /usr/share/sddm/themes/catppuccin-mocha-mauve"
    ".sddm/sddm.conf /etc/sddm.conf"
    ".vim"
    ".vscode/argv.json"
    ".bash_profile"
    ".bashrc"
    ".gitconfig"
    ".vimrc"
)
