declare -a INSTALL_PACKAGES=(
    "awww-git"                          # 
    "btop"                              # 
    "fastfetch"                         # 
    "gnome-keyring"                     # GNOME keyring for managing passwords and keys
    "hyprlock"                          # 
    "microsoft-edge-stable-bin"         # Binary package of Microsoft Edge browser
    "neovim"                            # Modern, extensible text editor based on Vim
    "network-manager-applet"            #  
    "networkmanager"                    # 
    "qt5-quickcontrols2"                # 
    "qt6-declarative"                   # 
    "qt6-svg"                           # 
    "rofi"                              # 
    "starship"                          #
    "ttf-jetbrains-mono-nerd"           # 
    "visual-studio-code-bin"            # Binary package of Visual Studio Code IDE
    "waybar"                            # Status bar for Wayland compositors
    "wlogout"                           # Logout/shutdown menu for Wayland
    # "bat"                               # Cat clone with syntax highlighting and Git integration
    # "btop"                              # Resource monitor (CPU, RAM, processes) with TUI
    # "dust"                              # Disk usage analyzer with a modern interface
    # "eza"                               # Modern replacement for `ls` with colors and icons
    # "fd"                                # Fast alternative to `find` for searching files
    # "just"                              # Command runner for managing and running project-specific tasks
    # "less"                              # Pager for viewing text files
    # "plocate"                           # Faster alternative to `locate` for file search
    # "plymouth"                          # Boot splash screen
    # "tldr"                              # Simplified man pages
    # "zoxide"                            # Smarter `cd` command for quick navigation
    # "whois"                             # WHOIS client for domain info
)

declare -a REMOVE_PACKAGES=(
    "iwd"                               # 
)

declare -a REPOSITORIES=(
    "xwildhagen/arch arch"
    "folke/lazy.nvim .local/share/nvim/lazy/lazy.nvim"
)
